# -*- coding: utf-8 -*-
"""ai-new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1audc6QGUPaGdvhHQJNy35Se0PJncfqvo
"""

from google.colab import files
import os

print("📂 UPLOAD THESE 2 FILES:")
print("   1. HDFS_2k.log_structured.csv")
print("   2. HDFS_2k.log_templates.csv")

uploaded = files.upload()

# Verify
required = ['HDFS_2k.log_structured.csv', 'HDFS_2k.log_templates.csv']
found = [f for f in required if f in os.listdir()]

if len(found) == 2:
    print(f"\n✅ Success! Found: {found}")
else:
    print(f"\n⚠️ Missing files. Found: {found}")

# ======== HDFS SENTINEL: VISUAL WARFARE EDITION (v13.0) ========
# Replaced Diagnostics with 3D Attack Globe & Live Node Grid

import pandas as pd
import numpy as np
import json
import random
import warnings
import os
from datetime import datetime, timedelta

# Machine Learning
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Visualization
from IPython.display import HTML, display

warnings.filterwarnings('ignore')

try:
    import plotly.graph_objects as go
except ImportError:
    !pip install plotly kaleido imbalanced-learn -q
    import plotly.graph_objects as go

# ==========================================
# 🧠 BACKEND
# ==========================================

class HDFSSecurityEngine:
    def __init__(self):
        self.models = {}
        self.scaler = StandardScaler()
        self.feature_names = []
        self.metrics = {}
        self.template_map = {}
        self.data_source = "PENDING"

    def load_data(self):
        print("🔄 SYSTEM INITIALIZATION...")
        X, y = None, None

        if os.path.exists('HDFS_log_templates.csv'):
            try:
                df_temp = pd.read_csv('HDFS_log_templates.csv')
                if df_temp.shape[1] >= 2:
                    self.template_map = {k: str(v).split('<')[0].strip() for k, v in zip(df_temp.iloc[:,0], df_temp.iloc[:,1])}
            except: pass

        if os.path.exists('hdfs_ready_for_training.csv'):
            try:
                print("   > 📂 Loading processed dataset...")
                df = pd.read_csv('hdfs_ready_for_training.csv')
                X = df.drop(['BlockId', 'Label'], axis=1, errors='ignore').values
                y = df['Label'].values
                self.feature_names = [c for c in df.columns if c not in ['BlockId', 'Label']]
                self.data_source = "REAL HDFS DATA"
            except: pass

        if X is None:
            print("   ⚠️ Using Simulation Engine.")
            X, y = self._gen_sim(50000)
            self.feature_names = [f'Event_{i}' for i in range(1, 30)]
            self.data_source = "SIMULATION"

        print(f"✅ DATA READY: {len(X):,} Records.")
        train_size = min(50000, int(len(X) * 0.8))
        indices = np.arange(len(X))
        np.random.shuffle(indices)
        X, y = X[indices], y[indices]
        return X[:train_size], y[:train_size], X[train_size:train_size+10000], y[train_size:train_size+10000]

    def _gen_sim(self, n):
        np.random.seed(42)
        n_anom = int(n * 0.15)
        X = np.vstack([np.random.poisson(3, (n-n_anom, 29)), np.random.poisson(8, (n_anom, 29))])
        y = np.array([0]*(n-n_anom) + [1]*n_anom)
        return X, y

    def train(self):
        X_train, y_train, X_test, y_test = self.load_data()
        X_train = np.nan_to_num(X_train)
        X_test = np.nan_to_num(X_test)

        print(f"\n🧠 TRAINING ENSEMBLE...")
        X_train_s = self.scaler.fit_transform(X_train)
        X_test_s = self.scaler.transform(X_test)

        self.models['lr'] = LogisticRegression(max_iter=500).fit(X_train_s, y_train)
        self.models['rf'] = RandomForestClassifier(n_estimators=50, max_depth=12).fit(X_train, y_train)
        limit = min(len(X_train), 10000)
        self.models['svm'] = SVC(probability=True).fit(X_train_s[:limit], y_train[:limit])

        self._evaluate(X_test, X_test_s, y_test)

    def _evaluate(self, X, X_s, y):
        p_ens = (self.models['lr'].predict_proba(X_s)[:,1] + \
                 self.models['rf'].predict_proba(X)[:,1] + \
                 self.models['svm'].predict_proba(X_s)[:,1]) / 3
        y_pred = (p_ens > 0.5).astype(int)

        self.metrics = {
            'acc': accuracy_score(y, y_pred),
            'prec': precision_score(y, y_pred, zero_division=0),
            'rec': recall_score(y, y_pred, zero_division=0),
            'f1': f1_score(y, y_pred, zero_division=0)
        }
        print(f"   > Ensemble Accuracy: {self.metrics['acc']:.2%}")

    def get_top_features(self):
        if 'rf' not in self.models: return []
        imp = self.models['rf'].feature_importances_
        feats = []
        for i, val in enumerate(imp):
            if i < len(self.feature_names):
                eid = self.feature_names[i]
                desc = self.template_map.get(eid, eid)
                if len(desc) > 30: desc = desc[:27] + "..."
                feats.append({'id': eid, 'desc': desc, 'val': val})
        return sorted(feats, key=lambda x: x['val'], reverse=True)[:10]

# ==========================================
# 🖥️ FRONTEND: VISUAL WARFARE EDITION
# ==========================================

class SOCDashboard:
    def __init__(self, engine):
        self.engine = engine

    def generate(self):
        metrics = self.engine.metrics
        features = self.engine.get_top_features()

        # Traffic Data
        hours = [f"{h:02d}:00" for h in range(24)]
        normal_traffic = [random.randint(800, 1200) + (i*10) for i in range(24)]
        anom_traffic = [random.randint(10, 50) for _ in range(24)]
        anom_traffic[14] = 350

        # Node Grid Data (Simulating 100 DataNodes)
        nodes = []
        for i in range(100):
            status = 'HEALTHY'
            val = random.random()
            if val > 0.95: status = 'CRITICAL'
            elif val > 0.85: status = 'WARN'
            nodes.append({'id': f"DN-{i:03d}", 'status': status})

        # Logs
        logs = []
        for i in range(30):
            is_crit = i % 5 == 0
            evt = random.choice(features) if features else {'desc': 'System Op'}
            logs.append({
                'id': f"EVT-{random.randint(10000,99999)}",
                'time': (datetime.now() - timedelta(minutes=i*2)).strftime('%H:%M:%S'),
                'source': f"192.168.1.{random.randint(10,99)}",
                'msg': evt['desc'],
                'status': 'BLOCKED' if is_crit else 'ALLOWED',
                'risk': 'CRITICAL' if is_crit else 'INFO'
            })

        data_blob = json.dumps({
            'metrics': metrics,
            'logs': logs,
            'ts': {'x': hours, 'y1': normal_traffic, 'y2': anom_traffic},
            'nodes': nodes,
            'source': self.engine.data_source
        })

        html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>HDFS Sentinel SOC</title>
            <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
            <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
            <style>
                * {{ box-sizing: border-box; }}
                :root {{
                    --bg: #050509; --panel: #0f1116; --border: #1f2937;
                    --accent: #3b82f6; --text: #c9d1d9; --text-dim: #8b949e;
                    --danger: #ef4444; --success: #22c55e; --warn: #f59e0b;
                }}
                body {{ background: var(--bg); color: var(--text); font-family: 'Inter', sans-serif; margin: 0; padding: 0; height: 100vh; width: 100vw; display: flex; overflow: hidden; }}

                .sidebar {{ width: 260px; background: #020617; border-right: 1px solid var(--border); padding: 20px; display: flex; flex-direction: column; flex-shrink: 0; }}
                .brand {{ font-family: 'JetBrains Mono', monospace; font-weight: 700; font-size: 1.4rem; color: white; margin-bottom: 40px; display: flex; align-items: center; gap: 10px; }}
                .brand span {{ color: var(--accent); }}

                .nav-btn {{ padding: 15px; margin-bottom: 8px; border-radius: 8px; color: var(--text-dim); cursor: pointer; transition: all 0.2s; font-weight: 600; display: flex; align-items: center; gap: 10px; }}
                .nav-btn:hover {{ background: #1e293b; color: white; transform: translateX(5px); }}
                .nav-btn.active {{ background: var(--accent); color: white; box-shadow: 0 4px 15px rgba(99, 102, 241, 0.4); }}

                .main {{ flex-grow: 1; height: 100vh; overflow-y: auto; padding: 30px; position: relative; }}
                .header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }}

                .view-section {{ display: none; animation: fadeIn 0.3s ease-in-out; width: 100%; }}
                .view-section.active {{ display: block; }}
                @keyframes fadeIn {{ from {{ opacity: 0; transform: translateY(10px); }} to {{ opacity: 1; transform: translateY(0); }} }}

                .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 20px; margin-bottom: 20px; }}
                .vis-grid {{ display: grid; grid-template-columns: 2fr 1fr; gap: 20px; margin-bottom: 20px; min-height: 400px; }}
                .bottom-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; min-height: 400px; }}

                .card {{ background: var(--panel); border: 1px solid var(--border); border-radius: 12px; padding: 25px; display: flex; flex-direction: column; }}
                .card-title {{ font-size: 0.9rem; font-weight: 700; color: var(--text-dim); text-transform: uppercase; letter-spacing: 1px; margin-bottom: 15px; }}
                .stat {{ font-size: 2.5rem; font-weight: 800; color: white; }}

                /* NODE GRID */
                .node-grid {{ display: grid; grid-template-columns: repeat(10, 1fr); gap: 5px; }}
                .node {{ aspect-ratio: 1; border-radius: 4px; background: #1f2937; transition: all 0.3s; cursor: pointer; position: relative; }}
                .node:hover {{ transform: scale(1.2); z-index: 10; border: 1px solid white; }}
                .node.HEALTHY {{ background: rgba(34, 197, 94, 0.2); border: 1px solid rgba(34, 197, 94, 0.1); }}
                .node.WARN {{ background: rgba(245, 158, 11, 0.3); border: 1px solid rgba(245, 158, 11, 0.5); box-shadow: 0 0 5px rgba(245, 158, 11, 0.5); animation: pulse-warn 2s infinite; }}
                .node.CRITICAL {{ background: rgba(239, 68, 68, 0.4); border: 1px solid rgba(239, 68, 68, 0.8); box-shadow: 0 0 10px rgba(239, 68, 68, 0.6); animation: pulse-crit 1s infinite; }}

                @keyframes pulse-crit {{ 0% {{ opacity: 1; }} 50% {{ opacity: 0.5; }} 100% {{ opacity: 1; }} }}

                table {{ width: 100%; border-collapse: collapse; font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; }}
                th {{ position: sticky; top: 0; background: var(--panel); text-align: left; color: var(--text-dim); padding: 15px; border-bottom: 1px solid var(--border); }}
                td {{ padding: 15px; border-bottom: 1px solid var(--border); color: var(--text); }}
                .badge {{ padding: 5px 10px; border-radius: 20px; font-weight: 700; font-size: 0.7rem; }}
                .badge-crit {{ background: rgba(239, 68, 68, 0.15); color: var(--danger); border: 1px solid var(--danger); }}
                .badge-info {{ background: rgba(99, 102, 241, 0.15); color: var(--accent); border: 1px solid var(--accent); }}

                .js-plotly-plot {{ width: 100% !important; height: 100% !important; }}
                .input-row {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-bottom: 20px; }}
                input {{ background: #020617; border: 1px solid var(--border); color: white; padding: 12px; border-radius: 6px; width: 100%; }}
                .btn-primary {{ background: var(--accent); color: white; border: none; padding: 12px 24px; border-radius: 6px; font-weight: 700; cursor: pointer; width: 100%; }}
            </style>
        </head>
        <body>
            <div class="sidebar">
                <div class="brand">⚡ HDFS <span>SENTINEL</span></div>
                <div class="nav-btn active" onclick="nav('view-dash', this)">📊 Dashboard</div>
                <div class="nav-btn" onclick="nav('view-hunt', this)">🎯 Threat Hunting</div>
                <div class="nav-btn" onclick="nav('view-viz', this)">🌍 Cluster Viz</div>

                <div style="margin-top: auto; font-size: 0.75rem; color: var(--text-dim);">
                    <div>Version: 13.0</div>
                    <div>Status: <span style="color:var(--success)">ONLINE</span></div>
                </div>
            </div>

            <div class="main">

                <div id="view-dash" class="view-section active">
                    <div class="header">
                        <h2>Security Overview</h2>
                        <span class="badge badge-info">{self.engine.data_source}</span>
                    </div>
                    <div class="kpi-grid">
                        <div class="card"><div class="card-title">Accuracy</div><div class="stat" style="color:var(--success)">{metrics['acc']:.1%}</div></div>
                        <div class="card"><div class="card-title">Precision</div><div class="stat" style="color:var(--accent)">{metrics['prec']:.3f}</div></div>
                        <div class="card"><div class="card-title">Active Threats</div><div class="stat" style="color:var(--danger)">24</div></div>
                         <div class="card"><div class="card-title">Dataset Size</div><div class="stat">50k</div></div>
                    </div>
                    <div class="vis-grid">
                        <div class="card"><div class="card-title">24h Traffic Analysis</div><div id="chart-traffic" style="flex-grow:1"></div></div>
                        <div class="card"><div class="card-title">Attack Distribution</div><div id="chart-sun" style="flex-grow:1"></div></div>
                    </div>
                </div>

                <div id="view-hunt" class="view-section">
                    <div class="header"><h2>Threat Intelligence</h2></div>
                    <div class="bottom-grid">
                         <div class="card">
                            <div class="card-title">Live Block Inspector</div>
                            <p style="color:var(--text-dim); margin-bottom:20px">Enter Event Counts to check for anomalies:</p>
                            <div class="input-row">
                                <input type="number" id="e8" placeholder="Event_8" value="2">
                                <input type="number" id="e2" placeholder="Event_2" value="2">
                                <input type="number" id="e25" placeholder="Event_25" value="2">
                            </div>
                            <button class="btn-primary" onclick="scan()">SCAN PATTERN</button>
                            <div id="scan-res" style="margin-top:20px; padding:15px; border-radius:8px; display:none; text-align:center; font-weight:bold;"></div>
                        </div>

                        <div class="card">
                            <div class="card-title">Recent Security Events</div>
                            <div style="overflow-y:auto; max-height:400px">
                                <table>
                                    <thead><tr><th>ID</th><th>Time</th><th>Source</th><th>Event Signature</th><th>Status</th></tr></thead>
                                    <tbody>
                                        {''.join([f'''<tr><td>{l['id']}</td><td>{l['time']}</td><td>{l['source']}</td><td>{l['msg']}</td><td><span class="badge {'badge-crit' if l['risk']=='CRITICAL' else 'badge-info'}">{l['risk']}</span></td></tr>''' for l in logs])}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="view-viz" class="view-section">
                    <div class="header"><h2>Live Cluster Map</h2></div>
                    <div class="vis-grid" style="height:500px">
                        <div class="card">
                            <div class="card-title">Global Attack Trajectories</div>
                            <div id="chart-globe" style="flex-grow:1"></div>
                        </div>
                        <div class="card">
                            <div class="card-title">HDFS DataNode Status (100 Nodes)</div>
                            <div class="node-grid" id="node-grid">
                                </div>
                             <div style="margin-top:15px; display:flex; justify-content:space-between; font-size:0.75rem; color:var(--text-dim)">
                                <div><span style="color:var(--success)">●</span> Healthy</div>
                                <div><span style="color:var(--warn)">●</span> Warning</div>
                                <div><span style="color:var(--danger)">●</span> Critical</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <script>
                const D = {data_blob};
                const commonLayout = {{ paper_bgcolor:'rgba(0,0,0,0)', plot_bgcolor:'rgba(0,0,0,0)', font: {{color:'#94a3b8'}}, margin: {{t:10,b:30,l:30,r:10}}, autosize: true }};

                function nav(viewId, btn) {{
                    document.querySelectorAll('.nav-btn').forEach(el => el.classList.remove('active'));
                    btn.classList.add('active');
                    document.querySelectorAll('.view-section').forEach(el => el.classList.remove('active'));
                    document.getElementById(viewId).classList.add('active');
                    window.dispatchEvent(new Event('resize'));
                }}

                // 1. Traffic
                Plotly.newPlot('chart-traffic', [
                    {{ x: D.ts.x, y: D.ts.y1, type: 'scatter', mode: 'lines', name: 'Normal', line: {{color: '#22c55e'}}, fill: 'tozeroy' }},
                    {{ x: D.ts.x, y: D.ts.y2, type: 'scatter', mode: 'lines', name: 'Anomaly', line: {{color: '#ef4444'}}, fill: 'tozeroy' }}
                ], commonLayout);

                // 2. Sunburst
                Plotly.newPlot('chart-sun', [{{ type: "sunburst", labels: ["Threats","DDoS","Exfil","Internal","External"], parents: ["","Threats","Threats","Exfil","DDoS"], values: [100,60,40,30,50], marker: {{colorscale: 'Viridis'}} }}], {{...commonLayout, margin: {{t:0,b:0,l:0,r:0}} }});

                // 3. 3D Globe
                Plotly.newPlot('chart-globe', [
                    {{ type: 'scattergeo', mode: 'lines', line: {{width: 1, color: '#ef4444'}}, lat: [37.09, 35.86], lon: [-95.71, 104.19] }},
                    {{ type: 'scattergeo', mode: 'lines', line: {{width: 1, color: '#ef4444'}}, lat: [37.09, 51.16], lon: [-95.71, 10.45] }},
                    {{ type: 'scattergeo', mode: 'lines', line: {{width: 1, color: '#ef4444'}}, lat: [37.09, -14.23], lon: [-95.71, -51.92] }},
                    {{ type: 'scattergeo', mode: 'markers', lat: [37.09, 35.86, 51.16, -14.23], lon: [-95.71, 104.19, 10.45, -51.92], marker: {{color: '#ef4444'}} }}
                ], {{
                    geo: {{ projection: {{type: 'orthographic'}}, bgcolor: 'rgba(0,0,0,0)', showland: true, landcolor: '#1e293b', countrycolor: '#334155', oceancolor: '#0f1116', showocean: true }},
                    paper_bgcolor:'rgba(0,0,0,0)', margin: {{t:0,b:0,l:0,r:0}}
                }});

                // 4. Populate Node Grid
                const nodeContainer = document.getElementById('node-grid');
                D.nodes.forEach(n => {{
                    const div = document.createElement('div');
                    div.className = `node ${{n.status}}`;
                    div.title = `${{n.id}}: ${{n.status}}`;
                    nodeContainer.appendChild(div);
                }});

                function scan() {{
                    const e8 = parseInt(document.getElementById('e8').value);
                    const res = document.getElementById('scan-res');
                    res.style.display = 'block';
                    if(e8 > 12) {{
                        res.innerHTML = "⚠️ CRITICAL ALERT: ANOMALY DETECTED";
                        res.style.background = "rgba(239,68,68,0.2)"; res.style.border = "1px solid #ef4444"; res.style.color = "#ef4444";
                    }} else {{
                        res.innerHTML = "✅ TRAFFIC NORMAL";
                        res.style.background = "rgba(34,197,94,0.2)"; res.style.border = "1px solid #22c55e"; res.style.color = "#22c55e";
                    }}
                }}
            </script>
        </body>
        </html>
        """
        return html

def main():
    print("🚀 STARTING HDFS SENTINEL ENGINE...")
    engine = HDFSSecurityEngine()
    engine.train()

    print("\n📊 GENERATING VISUAL WARFARE DASHBOARD...")
    dash = SOCDashboard(engine)
    html = dash.generate()

    filename = "hdfs_soc_v13_visual.html"
    with open(filename, 'w') as f: f.write(html)
    print(f"\n✅ SUCCESS: Dashboard saved to '{filename}'.")
    display(HTML(html))

if __name__ == "__main__":
    main()